version: '3'
services:
  php:
    build:
      context: docker/php
    volumes:
      - '.:/var/www/html'
      - './docker/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini'
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
    restart: always
    depends_on:
      - php
