package ru.mathparser;

public enum ParsingResult {
    ERROR,
    EXPRESSION,
    EXPLICIT_FUNCTION,
    EXPLICIT_FUNCTION_WITH_PARAMETERS,
    IMPLICIT_FUNCTION,
    IMPLICIT_FUNCTION_WITH_PARAMETERS,
    PARAMETRIC_FUNCTION,
    PARAMETRIC_FUNCTION_WITH_PARAMETERS
}
